# Site settings
title:                4clouds
tagline:              '4clouds'
description:          '4clouds'

# Build settings
url:                  http://localhost:4000
baseurl:              ''
markdown:             kramdown
highlighter:          pygments
permalink:            pretty
relative_permalinks:  true
sass:
    style: compressed
compress_html:
  clippings: none
  comments: ["<!-- ", " -->"]
  profile: false
  ignore:
    envs: [local]
exclude: ["README.md"]

# About/contact
author:
  name:               W.Regenczuk
  url:                https://wregen.github.io
  email:              W.Regenczuk@4clouds.io

# Custom vars
version:              1.1.0
