# Site settings
title:                '4clouds.io | zmigrujemy Twoje systemy i dane do chmury'
title_en:             '4clouds.io | move your business to the cloud'
tagline:              '4clouds'
description:          'Migracja do chmury. Bezpieczeństwo i koszty. Systemy i aplikacje.'
description_en:       'Cloud migration. Security and costs. Systems and applications.'

# Build settings
url:                  http://4clouds.io
baseurl:              ''
markdown:             kramdown
highlighter:          pygments
permalink:            pretty
relative_permalinks:  true
sass:
    style: compressed
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  profile: false
  ignore:
    envs: [local]
exclude: ["README.md"]

# About/contact
author:
  name:               W.Regenczuk
  url:                https://wregen.github.io
  email:              W.Regenczuk@4clouds.io

# Custom vars
version:              1.1.0
