# Site settings
title:                4clouds
tagline:              '4clouds'
description:          '4clouds'

# Build settings
url:                  http://192.168.0.12:4000
baseurl:              ''
markdown:             kramdown
highlighter:          pygments
permalink:            pretty
relative_permalinks:  true

exclude: ["README.md"]

# About/contact
author:
  name:               W.Regenczuk
  url:                https://wregen.github.io
  email:              W.Regenczuk@gmail.com

# Custom vars
version:              1.0.0
